### ISSUE TITLE
doi-synchronizer CLI doesn't work

### ISSUE THREAD

**Issue by MattBlissett** [gbif/registry#132]
```
./doi-synchronizer --fix-doi --doi 10.15468/six3fs
DEBUG [07-04 12:23:18,266+0000] [main] org.gbif.registry.cli.common.DataCiteConfiguration:  Creating RestJsonApiDataCite service
Command threw exception
java.lang.NullPointerException
        at org.gbif.registry.cli.common.CommonBuilder.createRestJsonApiDataCiteService(CommonBuilder.java:28)
        at org.gbif.registry.cli.doisynchronizer.DoiSynchronizerService.<init>(DoiSynchronizerService.java:72)
        at org.gbif.registry.cli.doisynchronizer.DoiSynchronizerService.<init>(DoiSynchronizerService.java:61)
        at org.gbif.registry.cli.doisynchronizer.DoiSynchronizerCommand.doRun(DoiSynchronizerCommand.java:27)
        at org.gbif.cli.BaseCommand.run(BaseCommand.java:137)
        at org.gbif.cli.Application.run(Application.java:97)
        at org.gbif.cli.Application.main(Application.java:146)
```

The purpose of this tool is to update the metadata for a DOI with newly generated metadata based on the registry information.

**Comment by mike-podolskiy90** [comment]
Is the parameter '--datacite-api' present? for prod it should be 'https://api.datacite.org/'
