### ISSUE TITLE
Can't run reinterpretation for some datasets using API

### ISSUE THREAD

**Issue by muttcg** [gbif/registry#468]
Registry logs

```
ERROR [2023-01-19 13:16:04,998+0000] [http-nio-8082-exec-131] org.gbif.registry.service.RegistryDatasetServiceImpl: Stored metadata document 679892 cannot be read
java.io.IOException: Wrong metadata type DC, use proper parser!
	at org.gbif.metadata.eml.parse.DatasetEmlParser.build(DatasetEmlParser.java:64)
	at org.gbif.registry.service.RegistryDatasetServiceImpl.getPreferredMetadataDataset(RegistryDatasetServiceImpl.java:293)
	at org.gbif.registry.service.RegistryDatasetServiceImpl.get(RegistryDatasetServiceImpl.java:115)
	at org.gbif.registry.service.RegistryDatasetServiceImpl$$FastClassBySpringCGLIB$$f8176858.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:55)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
	at org.gbif.registry.service.RegistryDatasetServiceImpl$$EnhancerBySpringCGLIB$$8a9a25fa.get(<generated>)
```

**Comment by muttcg** [comment]
Maybe related with the latest metadata code refactoring
